<a href="https://colab.research.google.com/github/zachakss/chess-rating-research/blob/main/FIDE_Chess_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = df[df["month"] == "September"].copy()

In [ ]:
df["age"] = 2025 - df["birth_year"]

In [ ]:
df = df[(df["age"] >= 5) & (df["age"] <= 100)]

In [ ]:
df.to_csv("fide_ratings_cleaned_september.csv", index=False)

In [ ]:
df.columns

Index(['id', 'name', 'federation', 'sex', 'title', 'rating', 'games',
       'birth_year', 'month', 'age'],
      dtype='object')

In [ ]:
df.shape

(203185, 10)

In [ ]:
df.isnull().sum()

id                 0
name               0
federation         0
sex                0
title         190517
rating             0
games              0
birth_year         0
month              0
age                0
dtype: int64

In [ ]:
df.head()

,id,name,federation,sex,title,rating,games,birth_year,month,age
201015,53707043,A Darshil,IND,M,NaN,1412,0,2013,September,12
201016,53200465,"A F M Ehteshamul, Hoque (tuhin",BAN,M,NaN,1797,0,1977,September,48
201017,5716365,"A Hamid, Harman",MAS,M,NaN,1552,0,1970,September,55
201018,53200553,A I Sabbir,BAN,M,NaN,1607,0,1995,September,30
201019,5045886,"A K, Kalshyan",IND,M,NaN,1747,0,1964,September,61